version: "3.8"

services:
  app:
    # build: .
    image: nishdoc1999/syvora-app:34
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=usersdb
      - PGHOST=db
      - PGPORT=5432
    command: npm start

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersdb
    ports:
      - "5432:5432"
